[package]
name = "el"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
oracle = "0.6.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.3+spec-1.1.0"
csv = "1.4"
anyhow = "1.0.102"
flate2 = "1.1.9"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-appender = "0.2"
chrono = "0.4"
